site_name: UGSEL Web Documentation
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo

nav:
  - Accueil: index.md
  - Architecture: architecture.md
  - Base de Donn√©es: database.md
  - Tests: tests.md
  - Guide Utilisateur: user_guide.md